name: Run tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run tests
        run: |
          yarn test
      - name: Send coverages
        uses: codecov/codecov-action@v2
